--- 
services: 
  elasticsearch: 
    cap_add: 
      - IPC_LOCK
    container_name: elasticsearch
    environment: 
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.2-arm64"
    ports: 
      - "9200:9200"
    restart: always
    ulimits: 
      memlock: 
        hard: -1
        soft: -1
      nofile: 
        hard: 65536
        soft: 65536
    volumes: 
      - "elasticsearch-data:/usr/share/elasticsearch/data"
  kibana: 
    container_name: kibana
    depends_on: 
      - elasticsearch
    environment: 
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    image: "docker.elastic.co/kibana/kibana:7.10.2"
    ports: 
      - "5601:5601"
    restart: always
    mem_limit: 1g
version: "3.3"
volumes: 
  elasticsearch-data: ~

